name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create ZIP
        run: |
          zip -r bf-utilities.zip . \
          --exclude ".git/*" \
          --exclude "node_modules/*" \
          --exclude ".husky/*" \
          --exclude ".github/*" \
          --exclude "tests/*" \
          --exclude ".editorconfig" \
          --exclude "eslint.config.mjs" \
          --exclude "*.d.ts" \
          --exclude "package-lock.json" \
          --exclude "tsconfig.json" \

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: bf-utilities.zip
          token: ${{ secrets.GITHUB_TOKEN }}